#!/bin/bash
#PBS -P mb26
#PBS -l ncpus=48,ngpus=4,mem=96gb
#PBS -l storage=scratch/mb26
#PBS -l walltime=2:00:00
#PBS -q gpuhopper
#PBS -m be
#PBS -l wd

cd /scratch/mb26/tv8394/workspace/zoology/
rm -rf wandb/*
rm log.txt

# export WANDB_API_KEY=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
export WANDB_MODE=offline
python -m zoology.launch zoology/experiments/kernel_deltanet/run_multiscale.py -p >> log.txt